version: '2'

services:
    web:
        image: httpd:2.4
        privileged: true
        ports:
            - "80:80"
        volumes:
            - /mnt/hgfs/github:/code
            - /mnt/hgfs/github/logs:/logs
            - ./conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        networks:
            - code-network
    tomcat:
        image: tomcat:8.5-jre8
        privileged: true
        ports:
            - "8080:8080"
        volumes:
            - /mnt/hgfs/github/pageoffice/JavaBridge:/usr/local/tomcat/webapps/JavaBridge
            - /mnt/hgfs/github/logs/tomcat:/usr/local/tomcat/logs
        networks:
            - code-network
    php:
        image: leoruslao/php-fpm:7.1
        privileged: true
        volumes:
        #    - ./php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker-php-core.ini:/usr/local/etc/php/conf.d/docker-php-core.ini
            - /mnt/hgfs/github:/code
        external_links:
            - jt_tomcat_1
        networks:
            - code-network
    mysql:
        image: mysql:5.7
        privileged: true
        volumes:
            - /usr/share/mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        networks:
            - code-network
    redis:
        image: redis:4.0.11
        privileged: true
        command: redis-server --requirepass mowork&201809
        ports:
            - "6379:6379"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
