version: "3"
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    restart: always
    hostname: '120.79.173.49'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://120.79.173.49:9090"
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - '9090:9090'
      - '2222:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
