version: '3'
services:
    jenkins:
        image: 'jenkins/jenkins:lts'
        container_name: jenkins
        user: root
        privileged: true
        restart: always
        ports:
          - '9999:8080'
          - '50000:50000'
        volumes:
          - '/home/jenkins_home:/var/jenkins_home'
          - '/etc/localtime:/etc/localtime'
          - './timezone:/etc/timezone'
